### ISSUE TITLE
No pretrained model

### ISSUE THREAD

**Issue by HeJunhong1107** [QizhiPei/FABind#1]
Could you please offer the pretained model？

**Comment by QizhiPei** [comment]
Hello:

Thanks for your interest in our work.

The pre-trained model is already provided. The following commands will automatically download the pre-trained model into the `ckpt` folder.

```
sudo apt-get install git-lfs # run this if you have not installed git-lfs
git lfs install
git clone https://github.com/QizhiPei/FABind.git --recursive
```

Or you can manually download it from https://huggingface.co/QizhiPei/FABind_model/tree/main.

**Comment by HeJunhong1107** [comment]
Thanks for your kind reminder, :)
