### ISSUE TITLE
Processing multiple smiles on one target

### ISSUE THREAD

**Issue by CLG68** [QizhiPei/FABind#10]
Hi,

This is not an issue per se, more a question and suggestions.

in your ex, the structure of the file is:
Cleaned_SMILES,pdb_id
CC[C@H](C)[C@H](NC(C)=O)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@H](C(=O)N[C@@H](CC(=O)O)C(=O)O)C(C)C,6efk
CC(C)CCN1c2nc(Nc3cc(F)c(O)c(F)c3)ncc2N(C)C(=O)C1(C)C,6g3c
CC(C)(CO[P@@](=O)(O)O[P@](=O)(O)OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)(O)O)[C@@H](O)C(=O)NCCC(=O)NCCO,6n93
O=C(O)c1ccccc1-n1cccc1,6npi

and the output are sd files with a name composed of pdb_id + a number. If I were to generate million of poses on one receptor... so on a virtual screen setup, it would be more practical that instead of the protein_id, it would be a compound id.  It is just a suggestion for an eventual update if you do not have already a screening mode.  If cmpd_id would be in the header than instead of appending a number to the name of the sd file, it would be the cmpd_id.

The poses generated are saved in sdf, can they be saved in mol2 files?  It is not a big problem as I can convert them but converting multi-million files takes some time so having them directly in mol2 files would save some time. as most of the rescoring tools accept mol2 files.

Best,
Christian

**Comment by QizhiPei** [comment]
Thanks for you suggestions.

For the name of the output file, we have updated the inference code and README according to your suggestions. We add a new column `ligand_id` to the input `.csv` file, which serves as the name of the output ligand file.

We also add the function to support saving `.mol2` file. As RDKit does not support saving mol object to `.mol2` file, the function supporting saving `.mol2` file is essentially a function that converts `.sdf` file to `.mol2` file based on openbabel package.
