### ISSUE TITLE
FABind+

### ISSUE THREAD

**Issue by CLG68** [QizhiPei/FABind#13]
Hi,

I just saw that [fabind_inference.py](https://github.com/QizhiPei/FABind/blob/main/fabind/fabind_inference.py) was updated 2 weeks ago.  Is it updated to FABind+ or it is just an update of FABind?  Are you going to create a new project for FABind+ or just update the FABind project?

Thank you,
Christian

**Comment by KyGao** [comment]
Hi, Thank you for your interest in our work.

The recent update to [fabind_inference.py](https://github.com/QizhiPei/FABind/blob/main/fabind/fabind_inference.py) is an update of FABind to support the saving of `.mol2` files and multiple compounds, as discussed in this [issue](https://github.com/QizhiPei/FABind/issues/10).

We are in the process of finalizing the training codes for FABind+ and plan to incorporate them into this repository.

**Comment by CLG68** [comment]
Thank you for your answer and for the updated version.  That previous issue/suggestion was from me but I missed your answer as I was in vacation.  I'll give it a try. 

I'll be very interested to test FABind+

Best,
Christian
