### ISSUE TITLE
return complex hidden features in inference

### ISSUE THREAD

**Issue by qwerthjkl45** [QizhiPei/FABind#14]
Return complex hidden features in inference so people can also use these features to do further prediction or other tasks.

**Comment by Nobody-Zhang** [comment]
Hi, @qwerthjkl45 

Thank you for your great idea that complex hidden features could be returned for downstream tasks!

Considering that returning them is not 'very' necessary in docking, however, I close this issue and the PR . But you can still develop it by adding the features in your own fork, and that is well recommended!
