### ISSUE TITLE
When will FABind+ be released?

### ISSUE THREAD

**Issue by GriffinYoung** [QizhiPei/FABind#16]
The README says soon, any idea when that would be? I'd be really interested in trying it!

**Comment by QizhiPei** [comment]
Thanks for your interest. We feel sorry for the delay and will provide the code of FABind+ in next few weeks.

**Comment by GriffinYoung** [comment]
Ok good to hear, thank you! Will the weights be released as well?

**Comment by QizhiPei** [comment]
Sure.

**Comment by Nobody-Zhang** [comment]
@GriffinYoung 
The code, scripts and weights are released today. Check it out!
