### ISSUE TITLE
problem with preprocessing smiles in FABind+

### ISSUE THREAD

**Issue by CLG68** [QizhiPei/FABind#17]
Hi, 

In FABind+ the processing of the ligand give me this error:

(fabind) christian@christian-linux01:/media/christian/VS/VS/VS_FABind_plus/fabind$ python inference_preprocess_mol_confs.py --index_csv ../inference_examples/example.csv --save_mols_dir ../inference_examples/temp_files
Traceback (most recent call last):
  File "inference_preprocess_mol_confs.py", line 22, in <module>
    smiles, pdb = line.strip().split(',')
ValueError: too many values to unpack (expected 2)

I think that originally the name of the molecule was not indicated in the smiles, now it contains 3 columns

If I preprocess a library of smiles and I want to reuse it with other targets, I guess I do not have to reprocess it again?

Thanks,
Christian

**Comment by Nobody-Zhang** [comment]
Hi, @CLG68 

Thank you for pointing out this problem we haven't noticed yet! 

I have fixed it by adding one more value named 'ligand_id' to unpack and it works.

As you can see, the '.pt' file contains a conformation generated with SMILES and a torch tensor 'molecule_info' containing information about the molecule( using 'extract_torchdrug_feature_from_mol' function ). So if you'd like to reuse them for some other purposes, no reprocessing is needed!

Thanks,
Gongbo Zhang

**Comment by Nobody-Zhang** [comment]
This issue will be closed marked as solved.
