### ISSUE TITLE
Sampling on custom complexes?

### ISSUE THREAD

**Issue by GriffinYoung** [QizhiPei/FABind#18]
The README shows how to do inference on custom complexes. Is there a way to do sampling on custom complexes? I only see the test_sampling_fabind.py file which doesn't seem designed for custom complexes.

**Comment by li-il-li** [comment]
First: Thanks for the great work, really like the direction!

I want to second this issue, though!
I don't fully grasp how to use the sampling based model (fabind+) for inference on custom complexes...
In the end I did cleanup the inference script and just plugged in the sampling based model, which seems to work.
But it would be great if there would be some clarification on how to approach that.

**Comment by GriffinYoung** [comment]
@Nobody-Zhang @QizhiPei any ideas on this?

**Comment by KyGao** [comment]
Hi, thank you for your interests in our work. we will release the sampling-based inference scripts in the next few days. Stay tuned!

**Comment by GriffinYoung** [comment]
Good to know, thank you!

**Comment by GriffinYoung** [comment]
@KyGao any update on this?

**Comment by KyGao** [comment]
Hi all, we have released the sampling-based inference scripts. Please check out our [README](https://github.com/QizhiPei/FABind/tree/main/FABind_plus#inference-on-custom-complexes-1).
