### ISSUE TITLE
Retraining FABind with custom data

### ISSUE THREAD

**Issue by Endyff** [QizhiPei/FABind#19]
Hi,
I love your work and I believe that your approach has big potential due to its speed. I am looking into retraining FABind with custom data. 

Is there somewhere a script to convert data to your required format and store into the _lmdb_ database? I am struggling to find the correct format.

Thanks, 
Ondrej Boucek

**Comment by QizhiPei** [comment]
Hi,
Thanks for your interest in FABind. We follow the same data processing as [TankBind data processing](https://github.com/luwei0917/TankBind/blob/main/examples/construction_PDBbind_training_and_test_dataset.ipynb), which will result in the `.pt` file. Then refer to the following code to convert `.pt` to `.lmdb` file.
```python
import lmdb
import pickle
import torch

def convert_dict_to_lmdb(dict_path, lmdb_path):
    # Load the dictionary
    with open(dict_path, 'rb') as f:
        data_dict = torch.load(f, map_location='cpu')

    # Save it as a lmdb database
    env = lmdb.open(lmdb_path, map_size=int(1e12))
    with env.begin(write=True) as txn:
        for key, value in data_dict.items():
            txn.put(key.encode(), pickle.dumps(value))
    env.close()

pre = '~/data/pdbbind2020/dataset/processed/'
convert_dict_to_lmdb(f'{pre}/protein.pt', f'{pre}/protein.lmdb')
print("protein done")
convert_dict_to_lmdb(f'{pre}/compound_LAS_edge_index.pt', f'{pre}/compound_LAS_edge_index.lmdb')
print("compound done")
convert_dict_to_lmdb(f'{pre}/esm2_t33_650M_UR50D.pt', f'{pre}/esm2_t33_650M_UR50D.lmdb')
print("esm done")
```
