### ISSUE TITLE
No CUDA runtime is found

### ISSUE THREAD

**Issue by bio-rat** [QizhiPei/FABind#2]
Hi, while running the inference script after installing all the required packages, I encountered this error. I do have an Nvidia GPU and it was working fine for other projects but not this time.
```
======  preprocess molecules  ======
No CUDA runtime is found, using CUDA_HOME='/usr/bin/nvcc'
======  preprocess proteins  ======

```

**Comment by QizhiPei** [comment]
Hi, thanks for your interest in our work.

The discussion in [this issue](https://github.com/open-mmlab/mmdetection/issues/281) may help solve your problem.

**Comment by bio-rat** [comment]
fixed it thank you!

**Comment by amaneer94** [comment]
@bio-rat , How did you fix it?
