### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by PinzhuoWu** [QizhiPei/FABind#3]
When running evaluation, an error occurs when iterating through the "new_dataset" in the test set at index 17300. The error message is as follows: 
![1703923755538](https://github.com/QizhiPei/FABind/assets/94941269/9da5d5b6-ce65-40de-99c1-d6b185155ad1)
![1703923807634](https://github.com/QizhiPei/FABind/assets/94941269/40032bae-08f7-4964-b5d0-df3cd1572dd3)

**Comment by QizhiPei** [comment]
I cannot reproduce your error. Could you rerun the code in a new machine with larger memory?

**Comment by PinzhuoWu** [comment]
Thank you for your suggestion, I'll give it a try.
