### ISSUE TITLE
Reproduciblity of Results with Inference Mode

### ISSUE THREAD

**Issue by asarigun** [QizhiPei/FABind#4]
Hi,

I'm quite impressed with the concept presented in your work; it has the potential to save considerable time. I attempted to replicate your model in inference mode, as described in README, but encountered discrepancies in both RMSD scores and visualizations compared to the reported results.

Here are the RMSD scores I obtained:

```bash
6g3c rmsd: 13.472411671189839
6npi rmsd: 13.028547491615917
```

Additionally, I observed differences in the docking visualizations between my replication attempts in inference mode and the results reported in your paper:

### PDB ID: 6G3C (Cyan=FABind, Yellow=Ground Truth, Purple=Diffdock)

| Reproduced with Inference                                                                                                | Reported in Paper                                                                                               |
|------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
| ![Reproduced](https://github.com/QizhiPei/FABind/assets/47702994/70e9d785-3740-4d42-abc5-13bd0acf9df6) | ![reported](https://github.com/QizhiPei/FABind/assets/47702994/3f355442-a89a-4344-846e-80b9f563005a) |

### PDB ID: 6NPI (Cyan=FABind, Yellow=Ground Truth, Purple=Diffdock)

| Reproduced with Inference                                                                                                | Reported in Paper                                                                                               |
|------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
| ![Reproduced](https://github.com/QizhiPei/FABind/assets/47702994/618b76af-9afa-4740-9264-7956f7e65f16) | ![reported](https://github.com/QizhiPei/FABind/assets/47702994/969099e0-11c8-4cf1-a8e2-da55b0c78a6a) |

Could you kindly offer any advice or insights on how to replicate your published results accurately?

Best regards,
Ahmet

**Comment by QizhiPei** [comment]
Hi Ahmet,

Thanks for your interest and questions in our work.
I have provide the my code about computing RMSD, processing input PDB files and other insights in the email. Please kindly check it.

Best regards,
Qizhi Pei
