### ISSUE TITLE
Does FABind provide some confidence/affinity score?

### ISSUE THREAD

**Issue by lindsey98** [QizhiPei/FABind#5]
Hi Qizhi,

   Does FABind provide some confidence/affinity score that I use to decide whether a pair of protein-ligand can bind or not? 
   I have tried setting the confidence score as 
   
```
pred_index_true = pocket_cls_pred[i][:j].sigmoid().unsqueeze(-1) # pocket predicted probability 
pred_index_false = 1. - pred_index_true
pred_index_prob = torch.cat([pred_index_false, pred_index_true], dim=-1)

pred_index_log_prob = torch.log(pred_index_prob)
pred_index_one_hot = gumbel_softmax_no_random(pred_index_log_prob,
                                                          tau=self.args.gs_tau,
                                                          hard=self.args.gs_hard)
pred_index_one_hot_true = pred_index_one_hot[:, 1].unsqueeze(-1)
pred_confidence_gumbel = pred_index_one_hot_true * pred_index_true
pred_pocket_confidence[i] = pred_confidence_gumbel.sum(dim=0) / pred_index_one_hot_true.sum(dim=0)
```
  However, I find the confidence scores are very high for arbitrary protein-ligand pairs, like > 0.9. 
  Therefore, I would like to ask if you have a better suggestion.

**Comment by QizhiPei** [comment]
Hi lindsey:

Thanks for your interest in our work.
This score you mentioned above is used to decide the probability of a amino acid belonging to the pocket in the data sample (i.e., each protein-ligand pair) level. 
However, in the docking problems, all the training samples are protein-ligand pairs with pocket, which means that there are only positive cases and no negative cases in the dataset (i.e., protein-ligand pairs) level.
Therefore, given an arbitrary protein-ligand pair, the pocket prediction model may still output high scores for some amino acid in the proteins.
Currently I do not think there are any available outputs in FABind that can used to decide whether a pair of protein-ligand can bind or not.

**Comment by lindsey98** [comment]
Thank you for your quick reply!
