### ISSUE TITLE
Alternatives to SMILES

### ISSUE THREAD

**Issue by agarrubio** [QizhiPei/FABind#6]
How can I start an inference using a pdb for the protien, and  a 'mol2' or 'sdf' file for the ligand?

**Comment by QizhiPei** [comment]
You can use the [read_molecule](https://github.com/HannesStark/EquiBind/blob/41bd00fd6801b95d2cf6c4d300cd76ae5e6dab5e/commons/process_mols.py#L1189) function from EquiBind to read the .sdf/mol2 file.
Then use `from rdkit import Chem; Chem.MolToSmiles(mol)`  to convert the mol object to its SMILES.
Hope this can help you~
