### ISSUE TITLE
No Results Written to uid_smiles_sdfname.csv After Running Inference on Custom Complexes

### ISSUE THREAD

**Issue by yukisoya** [QizhiPei/FABind#7]
After following the instructions provided in the README to run inference on custom complexes, I noticed that the uid_smiles_sdfname.csv file was created, but no results were written into it.

I suspect the issue may be related to an error encountered during the execution of post_optim_mol at line 371 in fabind_inference.py. To further investigate the problem, I removed the try block surrounding this part of the code. This action led to the generation of the following error message:

> Traceback (most recent call last):
  File "fabind_inference.py", line 382, in <module>
    post_optim_mol(args, accelerator, data, com_coord_pred, com_coord_pred_per_sample_list, com_coord_per_sample_list, compound_batch, LAS_tmp=LAS_tmp, rigid=args.rigid)
  File "fabind_inference.py", line 288, in post_optim_mol
    com_coord_i = data[i]['compound'].rdkit_coords
  File "/home/miniconda3/envs/fabind/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 177, in __getitem__
    return self.get_example(idx)  # type: ignore
  File "/home/miniconda3/envs/fabind/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 124, in get_example
    data = separate(
  File "/home/miniconda3/envs/fabind/lib/python3.8/site-packages/torch_geometric/data/separate.py", line 35, in separate
    attrs = slice_dict[key].keys()
KeyError: 'complex'

It seems the error might be preventing the successful writing of results to the uid_smiles_sdfname.csv file. Any assistance in resolving this issue and enabling the proper output to the file would be greatly appreciated.

**Comment by KyGao** [comment]
Hi, I suspect there is something wrong before this line of code. Have you checked the log for preprocessing molecules and proteins? Maybe you could retry the preprocessing steps and save the pt files in a new folder.

**Comment by EBGU** [comment]
I met the same problem. Try pip install torch_geometric==2.4.0. It works for me. Good luck!

**Comment by yukisoya** [comment]
@EBGU Thank you for your valuable suggestion! 
The issue was resolved by downgrading the version of torch_geometric from 2.5.0.
Your input is greatly appreciated!
