### ISSUE TITLE
Binding scores?

### ISSUE THREAD

**Issue by CLG68** [QizhiPei/FABind#9]
Hi,

I was able to run your examples w/o problems.  However, I did not find a file that contains the binding scores.  Is FABind generating only poses and then I need to use a rescoring tool such as BR-Nib to sort the binding poses?

Thanks for you help,
Christian

**Comment by QizhiPei** [comment]
Thanks for your interest in our work. Currently FABind is not able to output the binding score for the ligand-protein complex. External tools may be required to do so.

Feel free to contact for any further questions or discussions.
